begin;
select set_config('test.emy',(select id::text from bv_profiles where username='emy'),true),set_config('test.ceo',(select id::text from bv_profiles where username='mohamed.zidan'),true),set_config('test.oscar',(select id::text from bv_profiles where username='oscar'),true),set_config('test.youssef',(select id::text from bv_profiles where username='youssef'),true),set_config('test.members',(select count(*)::text from bv_profiles where active),true);
set local role authenticated;
do $test$
declare tid uuid; aid uuid; v int; payload jsonb; result jsonb; mid bigint; nid bigint; denied bool; token uuid:=gen_random_uuid();
begin
 perform set_config('request.jwt.claim.sub',current_setting('test.ceo'),true);
 result:=public.bv_action('create_task',jsonb_build_object('title','__chat_upgrade_test__','brief','Rollback test','drive_url','https://drive.google.com/folders/test','due_at',clock_timestamp()+interval '1 day'));tid:=(result->>'id')::uuid;
 select version into v from public.bv_tasks where id=tid;
 perform public.bv_action('assign',jsonb_build_object('task_id',tid,'version',v,'user_ids',jsonb_build_array(current_setting('test.ceo'),current_setting('test.emy'))));
 assert (select count(*)=2 from public.bv_assignments where task_id=tid),'CEO and EMY both receive assignments';
 select id into aid from public.bv_assignments where task_id=tid and user_id=auth.uid();
 select version into v from public.bv_tasks where id=tid;
 perform public.bv_action('start',jsonb_build_object('task_id',tid,'version',v,'assignment_id',aid));
 assert (select status='working' from public.bv_assignments where id=aid),'CEO starts own timer';
 perform set_config('request.jwt.claim.sub',current_setting('test.youssef'),true);
 assert exists(select 1 from public.bv_notifications where user_id=auth.uid() and kind='task' and task_id is null),'unassigned member gets generic team notification';
 assert not exists(select 1 from public.bv_tasks where id=tid),'unassigned member cannot see task details';
 perform set_config('request.jwt.claim.sub',current_setting('test.oscar'),true);
 payload:=jsonb_build_object('recipient_id',current_setting('test.emy'),'body','__private_rollback_message__','client_id',token);
 result:=public.bv_communicate('send',payload);mid:=(result->>'id')::bigint;
 assert (public.bv_communicate('send',payload)->>'id')::bigint=mid,'retry returns same message';
 assert (select count(*)=1 from public.bv_messages where sender_id=auth.uid() and client_id=token),'retry does not duplicate message';
 perform set_config('request.jwt.claim.sub',current_setting('test.ceo'),true);
 assert not exists(select 1 from public.bv_messages where id=mid),'CEO cannot read private conversation of others';
 assert not exists(select 1 from public.bv_notifications where message_id=mid),'CEO cannot read private message alert of others';
 perform set_config('request.jwt.claim.sub',current_setting('test.emy'),true);
 assert exists(select 1 from public.bv_messages where id=mid and body='__private_rollback_message__'),'recipient reads stored message';
 select id into nid from public.bv_notifications where message_id=mid;
 assert nid is not null,'notification saved atomically';
 perform public.bv_communicate('read_chat',jsonb_build_object('peer_id',current_setting('test.oscar'),'through',mid));
 assert (select read_at is not null from public.bv_messages where id=mid),'read receipt saved';
 assert (select read_at is not null from public.bv_notifications where id=nid),'alert read state saved';
 denied:=false;begin insert into public.bv_messages(client_id,sender_id,recipient_id,body) values(gen_random_uuid(),auth.uid(),current_setting('test.oscar')::uuid,'bypass');exception when insufficient_privilege then denied:=true;end;assert denied,'direct message writes blocked';
 perform set_config('request.jwt.claim.sub',current_setting('test.oscar'),true);
 assert (select read_at is not null from public.bv_messages where id=mid),'sender sees read receipt';
 perform set_config('request.jwt.claim.sub','',true);
 denied:=false;begin perform public.bv_communicate('send',payload);exception when raise_exception then denied:=true;end;assert denied,'unauthenticated send rejected';
end $test$;
select 'PASS: CEO/EMY assignment, CEO timer, generic team alerts, private chat, other-CEO isolation, idempotency, read receipts, notification persistence, write restrictions' checks;
rollback;
