begin;
select set_config('test.emy',(select id::text from bv_profiles where username='emy'),true),set_config('test.ceo',(select id::text from bv_profiles where username='mohamed.zidan'),true),set_config('test.oscar',(select id::text from bv_profiles where username='oscar'),true),set_config('test.youssef',(select id::text from bv_profiles where username='youssef'),true);
set local role authenticated;
do $test$
declare tid uuid; rid uuid; aid uuid; v int; result jsonb; denied bool; payload jsonb;
begin
 perform set_config('request.jwt.claim.sub',current_setting('test.emy'),true);
 payload:=jsonb_build_object('title','__transaction_verification__','brief','Verification only','drive_url','https://drive.google.com/folders/test','due_at',clock_timestamp()+interval '1 day');
 result:=public.bv_action('create_task',payload); tid:=(result->>'id')::uuid;
 assert result->>'ok'='true','create task acknowledgment';
 denied:=false;begin perform public.bv_action('create_task',payload||'{"drive_url":""}'::jsonb);exception when check_violation then denied:=true;end; assert denied,'missing Drive link rejected';
 select version into v from public.bv_tasks where id=tid;
 payload:=jsonb_build_object('task_id',tid,'version',v,'user_ids',jsonb_build_array(current_setting('test.oscar')));
 denied:=false;begin perform public.bv_action('assign',payload);exception when raise_exception then denied:=true;end;assert denied,'EMY cannot assign';
 perform set_config('request.jwt.claim.sub',current_setting('test.ceo'),true);
 perform public.bv_action('assign',payload);
 perform set_config('request.jwt.claim.sub',current_setting('test.oscar'),true);
 select id into aid from public.bv_assignments where task_id=tid;
 select version into v from public.bv_tasks where id=tid;
 perform public.bv_action('start',jsonb_build_object('task_id',tid,'version',v,'assignment_id',aid));
 select version into v from public.bv_tasks where id=tid;
 payload:=jsonb_build_object('task_id',tid,'version',v,'assignment_id',aid);
 denied:=false;begin perform public.bv_action('pause',payload);exception when raise_exception then denied:=true;end;assert denied,'employee cannot pause';
 perform set_config('request.jwt.claim.sub',current_setting('test.ceo'),true);
 perform public.bv_action('pause',payload);
 assert (select running_since is null and status='paused' from public.bv_assignments where id=aid),'timer stopped';
 select version into v from public.bv_tasks where id=tid;
 perform set_config('request.jwt.claim.sub',current_setting('test.oscar'),true);
 perform public.bv_action('submit',jsonb_build_object('task_id',tid,'version',v,'assignment_id',aid,'submission_url','https://drive.google.com/file/d/test'));
 select version into v from public.bv_tasks where id=tid;
 denied:=false;begin perform public.bv_action('approve',jsonb_build_object('task_id',tid,'version',v));exception when raise_exception then denied:=true;end;assert denied,'employee cannot approve';
 result:=public.bv_action('create_request','{"kind":"complaint","title":"__transaction_verification__","body":"Complaint persistence check"}');rid:=(result->>'id')::uuid;
 assert exists(select 1 from jsonb_array_elements(public.bv_state()->'requests') x where x->>'id'=rid::text),'creator reads complaint through state API';
 perform set_config('request.jwt.claim.sub',current_setting('test.youssef'),true);
 assert not exists(select 1 from public.bv_requests where id=rid),'other employee cannot read complaint';
 perform set_config('request.jwt.claim.sub',current_setting('test.ceo'),true);
 perform public.bv_action('approve',jsonb_build_object('task_id',tid,'version',v));
 perform public.bv_action('update_request',jsonb_build_object('id',rid,'status','done','response','Resolved'));
 perform set_config('request.jwt.claim.sub',current_setting('test.oscar'),true);
 assert exists(select 1 from public.bv_requests where id=rid and status='done' and response='Resolved'),'creator sees saved CEO response';
 denied:=false;begin update public.bv_requests set status='open' where id=rid;exception when insufficient_privilege then denied:=true;end;assert denied,'direct write denied';
end $test$;
select 'PASS: task creation, required Drive, assignment, timer, delivery, approval, complaint save/read/privacy/response, direct-write protection' as checks;
rollback;
