'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {supabase,accountAction} from '@/lib/supabase';
import {type State,type Profile,type Task,type Assignment,type RequestItem,roleLabel,statusLabel,currentAssignments,status,ms,duration,date,localDate} from '@/lib/types';
import Login from './login';
import Communication from './communication';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {Trash2,Plus,Clock3,ArrowUpLeft,FolderOpen,Play,Pause,Check,RotateCcw,LogOut,Users,ClipboardList,MessageSquare,LockKeyhole,CalendarDays,Link as LinkIcon,AlertCircle,RefreshCw,Settings2,Send,ChevronLeft,Timer} from 'lucide-react';
const initial:State={server_time:'',profiles:[],tasks:[],assignments:[],requests:[],activity:[]};
const kinds:Record<string,string>={equipment:'جهاز أو أدوات ناقصة',fault:'عطل في جهاز',complaint:'شكوى',other:'طلب آخر'};
const requestLabels:Record<string,string>={open:'طلب جديد',progress:'قيد التنفيذ',done:'تم التنفيذ'};
const initials=(n:string)=>n.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();
const fd=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form).entries());
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
function Pick({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:Record<string,string>}){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(items).map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select>;}
function Badge({value}:{value:string}){return <span className={'status status-'+value}>{statusLabel[value]||requestLabels[value]||value}</span>;}

export default function Workspace(){
 const [userId,setUserId]=useState<string|null>(null),[authReady,setAuthReady]=useState(false),[loaded,setLoaded]=useState(false);
 const [data,setData]=useState<State>(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connection,setConnection]=useState('connecting');
 const [tab,setTab]=useState('tasks'),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState(''),[target,setTarget]=useState<any>(null);
 const [now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[checks,setChecks]=useState<string[]>([]),[choice,setChoice]=useState('equipment'),[active,setActive]=useState(true);
 const mutationLock=useRef(false);
 const refreshSeq=useRef(0),currentUser=useRef<string|null>(null);currentUser.current=userId;
 const refresh=useCallback(async()=>{
  const uid=currentUser.current;if(!uid)return;
  const seq=++refreshSeq.current;
  const {data:s,error:e}=await supabase.rpc('bv_state');
  if(seq!==refreshSeq.current||uid!==currentUser.current)return;
  if(e){setError('تعذر تحديث البيانات. تأكد من اتصالك وحاول تاني.');return false;}
  const mine=(s as State).profiles.find(p=>p.id===uid);
  if(!mine?.active){setData(initial);setError('حسابك غير مفعّل في الفريق. تواصل مع الإدارة.');setLoaded(true);return;}
  setData(s);setOffset(Date.parse(s.server_time)-Date.now());setError('');setLoaded(true);return true;
 },[]);
 useEffect(()=>{
  supabase.auth.getSession().then(({data:{session}})=>{setUserId(session?.user.id??null);setAuthReady(true);});
  const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,session)=>{setUserId(session?.user.id??null);setAuthReady(true);if(!session){setData(initial);setSelected(null);setLoaded(false);setTab('tasks');setModal('');setTarget(null);}});
  return()=>subscription.unsubscribe();
 },[]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{
  if(!userId)return;setLoaded(false);void refresh();let debounce:ReturnType<typeof setTimeout>;
  const reload=()=>{clearTimeout(debounce);debounce=setTimeout(()=>void refresh(),100);};
  let channel=supabase.channel('brivviant-'+userId);
  for(const table of ['bv_profiles','bv_tasks','bv_assignments','bv_requests','bv_activity'])channel=channel.on('postgres_changes',{event:'*',schema:'public',table},reload);
  channel.subscribe(s=>{setConnection(s==='SUBSCRIBED'?'live':'connecting');if(s==='SUBSCRIBED')reload();});
  const periodic=setInterval(()=>{if(!document.hidden)void refresh();},30000);
  const focus=()=>void refresh();window.addEventListener('focus',focus);window.addEventListener('online',focus);
  return()=>{clearTimeout(debounce);clearInterval(periodic);void supabase.removeChannel(channel);window.removeEventListener('focus',focus);window.removeEventListener('online',focus);};
 },[userId,refresh]);
 const me=data.profiles.find(p=>p.id===userId),ceo=['ceo','team_leader'].includes(me?.role||''),canCreate=ceo||me?.role==='coordinator';
 const time=now+offset,t=data.tasks.find(x=>x.id===selected);
 const name=(id:string)=>data.profiles.find(x=>x.id===id)?.name||'عضو الفريق';
 const invoke=async(action:string,p:Record<string,unknown>)=>{const {data:r,error:e}=await supabase.rpc('bv_action',{p_action:action,p});if(e)throw new Error(e.message);if(!r?.ok||!r?.id)throw new Error('لم يؤكد السيرفر الحفظ. حدّث البيانات قبل المحاولة مرة أخرى.');return r;};
 async function run(action:string,p:Record<string,unknown>){if(mutationLock.current)return;mutationLock.current=true;setBusy(true);try{await invoke(action,p);setModal('');if(action==='delete_task')setSelected(null);const synced=await refresh();toast.success(synced?'تم حفظ التغيير':'تم الحفظ على السيرفر. تعذر تحديث العرض؛ اضغط تحديث.');}catch(e){toast.error(e instanceof Error?e.message:'تعذر تنفيذ الإجراء.');}finally{mutationLock.current=false;setBusy(false);}}
 async function manage(body:Record<string,unknown>){if(mutationLock.current)return;mutationLock.current=true;setBusy(true);try{await accountAction(body);setModal('');const synced=await refresh();toast.success(synced?'تم حفظ التغيير':'تم الحفظ على السيرفر. اضغط تحديث لعرض التغيير.');}catch(e){toast.error(e instanceof Error?e.message:'تعذر تنفيذ الإجراء.');}finally{mutationLock.current=false;setBusy(false);}}
 const open=(value:string,item?:any)=>{setTarget(item||null);setModal(value);if(value==='assign'&&t)setChecks(currentAssignments(t,data).map(a=>a.user_id));if(value==='request')setChoice('equipment');if(value==='user'){setChoice(item?.role||'employee');setActive(item?.active??true);}if(value==='handle_request')setChoice(item.status);};
 const taskPayload=()=>({task_id:t?.id,version:t?.version});
 const late=(task:Task)=>Date.parse(task.due_at)<time&&!['approved','review'].includes(status(task,data));
 useEffect(()=>{
  const ctx=(document as any).modelContext;if(!ctx?.registerTool||!me||me.must_change)return;
  const life=new AbortController();
  Promise.resolve(ctx.registerTool({name:'list_my_studio_tasks',title:'عرض التاسكات المتاحة',description:'Read the tasks visible to the signed-in Brivviant account. Does not modify tasks.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return data.tasks.map(x=>({id:x.id,title:x.title,status:status(x,data),due_at:x.due_at}));}},{signal:life.signal})).catch(()=>{});
  return()=>life.abort();
 },[data,me]);
 if(!authReady)return <main className="loading-shell"><Skeleton className="h-16 w-72"/><Skeleton className="h-64 w-full"/></main>;
 if(!userId)return <Login/>;
 if(!loaded)return <main className="loading-shell"><h1>جاري فتح مساحة الفريق…</h1><Skeleton className="h-64 w-full"/>{error&&<><p role="alert">{error}</p><Button onClick={refresh}>إعادة المحاولة</Button><Button variant="outline" onClick={()=>supabase.auth.signOut()}>خروج</Button></>}</main>;
 if(!me)return <main className="loading-shell"><LockKeyhole/><h1>الحساب غير متاح</h1><p>{error}</p><Button onClick={()=>supabase.auth.signOut()}>تسجيل الخروج</Button></main>;
 if(me.must_change)return <main className="password-page"><Toaster richColors position="top-center" dir="rtl"/><form className="panel password-box" onSubmit={e=>{e.preventDefault();const f=fd(e.currentTarget);if(f.password!==f.confirm){toast.error('كلمتا المرور غير متطابقتين.');return;}void manage({action:'change_password',current_password:f.current_password,password:f.password});}}><LockKeyhole/><h1>أهلًا {me.name}</h1><p>غيّر كلمة المرور المؤقتة قبل دخول مساحة الفريق.</p><Field label="كلمة المرور المؤقتة"><Input name="current_password" type="password" autoComplete="current-password" required/></Field><Field label="كلمة مرور جديدة — 12 حرفًا على الأقل"><Input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></Field><Field label="تأكيد كلمة المرور"><Input name="confirm" type="password" autoComplete="new-password" required/></Field><Button disabled={busy}>حفظ ودخول</Button><Button type="button" variant="ghost" onClick={()=>supabase.auth.signOut()}>تسجيل الخروج</Button></form></main>;
 const visible=data.tasks.filter(x=>filter==='all'||filter==='late'&&late(x)||status(x,data)===filter);
 return <div className="workspace"><Toaster richColors position="top-center" dir="rtl"/>
  <header className="topbar"><div className="brand-mini"><img src="brivviant-logo.png" alt="Brivviant Studios"/><span>مساحة الفريق</span></div><div className="topbar-end"><Communication key={me.id} me={me} profiles={data.profiles} onTask={id=>{setTab('tasks');setSelected(id);void refresh();}} onRequests={()=>setTab('requests')}/><span className={'connection '+(connection==='live'&&!error?'live':'offline')}>{connection==='live'&&!error?'متصل لحظيًا':'جاري إعادة الاتصال'}</span><button className="account-mini" onClick={()=>open('password')} title="تغيير كلمة المرور"><span className="avatar">{initials(me.name)}</span><span><b dir="ltr">{me.name}</b><small>{roleLabel[me.role]}</small></span></button><Button variant="ghost" size="icon" aria-label="تسجيل الخروج" onClick={()=>supabase.auth.signOut()}><LogOut size={19}/></Button></div></header>
  <main className="main-work"><div className="heading-row"><div><p className="eyebrow">STUDIO / WORKSPACE</p><h1>{ceo?'كل الشغل، قدامك.':me.role==='coordinator'?'من البريف لبداية الشغل.':'شغلك وتسليماتك.'}</h1><p className="muted">{new Intl.DateTimeFormat('ar-EG',{weekday:'long',day:'numeric',month:'long'}).format(new Date(now))}</p></div>{canCreate&&<Button className="primary-action" onClick={()=>open('create')}><Plus size={18}/>تاسك جديد</Button>}</div>
  {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/>{error}<Button size="sm" variant="outline" onClick={refresh}><RefreshCw size={15}/>تحديث</Button></div>}
  <Tabs value={tab} onValueChange={setTab} dir="rtl"><TabsList className="main-tabs"><TabsTrigger value="tasks"><ClipboardList size={18}/>التاسكات</TabsTrigger><TabsTrigger value="requests"><MessageSquare size={18}/>{ceo?'الطلبات والشكاوى':'طلباتي'}</TabsTrigger>{ceo&&<><TabsTrigger value="team"><Users size={18}/>الفريق والنقاط</TabsTrigger><TabsTrigger value="activity"><ClipboardList size={18}/>سجل النشاط</TabsTrigger></>}</TabsList>
  <TabsContent value="tasks"><div className="stats-grid">{[
   ['all','إجمالي التاسكات',data.tasks.length,FolderOpen],['unassigned','بانتظار التوزيع',data.tasks.filter(x=>status(x,data)==='unassigned').length,Users],['working','شغال دلوقتي',data.tasks.filter(x=>status(x,data)==='working').length,Timer],['review',ceo?'بانتظار اعتمادك':'بانتظار الاعتماد',data.tasks.filter(x=>status(x,data)==='review').length,Check],['late','متأخر عن التسليم',data.tasks.filter(late).length,AlertCircle]
  ].map(([key,label,count,Icon]:any)=><button key={key} className={'stat-card '+(filter===key?'selected':'')+' '+(key==='late'&&count?'late':'')} onClick={()=>setFilter(key)}><span>{label}<Icon size={19}/></span><strong>{String(count).padStart(2,'0')}</strong></button>)}</div>
  <section className="panel tasks-panel"><div className="panel-header"><h2>{filter==='all'?'كل التاسكات':filter==='late'?'التاسكات المتأخرة':statusLabel[filter]}</h2><span className="muted">{visible.length} تاسك</span>{filter!=='all'&&<Button variant="ghost" size="sm" onClick={()=>setFilter('all')}>عرض الكل</Button>}</div>
  {!visible.length?<div className="empty-state"><FolderOpen size={36}/><h3>{filter==='all'?'مفيش تاسكات لسه':'مفيش تاسكات بالحالة دي'}</h3><p>{canCreate?'أضف تاسك بالبريف وميعاد التسليم عشان تبدأ دورة الشغل.':'التاسكات المسندة ليك هتظهر هنا.'}</p>{canCreate&&<Button onClick={()=>open('create')}><Plus size={16}/>إضافة تاسك</Button>}</div>:<div className="task-list">{visible.map(task=>{const as=currentAssignments(task,data),st=status(task,data),running=as.some(a=>a.status==='working');return <button className="task-row" key={task.id} onClick={()=>setSelected(task.id)}><span className={'task-glyph '+(running?'is-running':'')}><FolderOpen size={23}/></span><span className="task-title"><b>{task.title}</b><small>{as.length?as.map(a=>name(a.user_id)).join(' · '):'بانتظار توزيع الإدارة'}{task.round>1?` · تعديل ${task.round-1}`:''}</small></span><Badge value={st}/><span className={'task-deadline '+(late(task)?'overdue':'')}><CalendarDays size={16}/><span>{date(task.due_at)}<small>{late(task)?'فات موعد التسليم':'موعد التسليم'}</small></span></span><span className="task-time"><Clock3 size={16}/><b dir="ltr">{duration(as.reduce((s,a)=>s+ms(a,time),0))}</b><small>وقت الفريق</small></span><ChevronLeft size={18}/></button>;})}</div>}</section></TabsContent>
  <TabsContent value="requests"><div className="section-title"><h2>{ceo?'طلبات الفريق والشكاوى':'طلباتي وشكاواي'}</h2><Button onClick={()=>open('request')}><Plus size={17}/>طلب جديد</Button></div>{!data.requests.length?<div className="panel empty-state"><MessageSquare size={34}/><h3>مفيش طلبات لسه</h3><p>قدّم طلب جهاز، بلّغ عن عطل، أو ابعت شكوى للإدارة.</p></div>:<div className="panel request-table-wrap"><table className="request-table"><thead><tr><th>صاحب الطلب</th><th>النوع</th><th>الطلب / الشكوى</th><th>الحالة</th><th>تاريخ الإرسال</th><th>وقت التنفيذ</th>{ceo&&<th>إدارة</th>}</tr></thead><tbody>{data.requests.map(q=><tr key={q.id}><td><b>{name(q.created_by)}</b></td><td>{kinds[q.kind]}</td><td><b>{q.title}</b><small className="table-detail">{q.body}</small>{q.response&&<small className="response-inline">رد الإدارة: {q.response}</small>}</td><td><Badge value={q.status}/></td><td>{date(q.created_at)}</td><td>{q.execution_due_at?<><b>{date(q.execution_due_at)}</b>{q.approved_at&&<small className="table-detail">اعتمد: {date(q.approved_at)}</small>}</>:'—'}</td>{ceo&&<td><div className="button-row"><Button size="sm" variant="outline" onClick={()=>open('handle_request',q)}>متابعة</Button><Button size="sm" variant="destructive" onClick={()=>{if(confirm('حذف الطلب/الشكوى؟'))void run('delete_request',{id:q.id});}}>حذف</Button></div></td>}</tr>)}</tbody></table></div>}</TabsContent>
  {ceo&&<TabsContent value="team"><div className="section-title"><div><h2>الفريق والنقاط</h2><p className="muted">النقاط محسوبة نسبيًا حسب مدة كل تاسك، سواء ساعتين أو يومين.</p></div><Button onClick={()=>open('user')}><Plus size={17}/>إضافة عضو</Button></div><div className="team-grid">{data.profiles.map(p=>{const history=data.assignments.filter(a=>a.user_id===p.id&&a.submitted_at).sort((a,b)=>Date.parse(b.submitted_at!)-Date.parse(a.submitted_at!));const points=history.reduce((sum,a)=>sum+Number(a.points_awarded||0),0);return <article className="panel member-card" key={p.id}><span className="avatar large">{initials(p.name)}</span><h3 dir="ltr">{p.name}</h3><p dir="ltr" className="muted">{p.username}</p><div className="member-score"><strong>{points}</strong><small>نقطة</small></div><span className="role-tag">{roleLabel[p.role]}</span><p className="member-status">{!p.active?'الحساب معطل':p.must_change?'بانتظار تغيير كلمة المرور':'الحساب مفعّل'}</p><div className="recent-submissions"><b>آخر التسليمات</b>{history.slice(0,5).length?history.slice(0,5).map(a=>{const task=data.tasks.find(t=>t.id===a.task_id);return <div className="submission-mini" key={a.id}><span>{task?.title||'تاسك مؤرشف'}</span><strong>+{a.points_awarded||0}</strong><small>{date(a.submitted_at!)}{a.points_reason?` · ${a.points_reason}`:''}{a.delay_reason?` · سبب التأخير: ${a.delay_reason}`:''}</small></div>}):<small className="muted">لا توجد تسليمات بعد.</small>}</div><div className="button-row"><Button variant="outline" onClick={()=>open('user',p)}><Settings2 size={16}/>إدارة</Button>{p.id!==me.id&&<Button variant="ghost" onClick={()=>open('reset',p)}><LockKeyhole size={16}/>باسورد</Button>}</div></article>})}</div></TabsContent>}
  {ceo&&<TabsContent value="activity"><div className="section-title"><div><h2>سجل النشاط</h2><p className="muted">كل تشغيل وإيقاف واستلام وتسليم واعتماد وطلب وحذف محفوظ في Supabase.</p></div></div><div className="panel activity-admin-list">{data.activity.length?data.activity.map(a=>{const task=a.task_id?data.tasks.find(t=>t.id===a.task_id):null;const req=a.request_id?data.requests.find(r=>r.id===a.request_id):null;return <div className="activity-admin-row" key={a.id}><span className="activity-line"/><b>{a.action}</b><span>{name(a.actor)}</span><small>{task?.title||req?.title||(a.task_id?'تاسك مؤرشف':a.request_id?'طلب/شكوى محذوفة':'النظام')} · {date(a.created_at)}</small>{a.detail&&<p className="prewrap">{a.detail}</p>}</div>}):<div className="empty-state"><ClipboardList size={34}/><h3>لا يوجد نشاط بعد</h3></div>}</div></TabsContent>}
  </Tabs><footer className="workspace-footer"><span>Brivviant Studios · V6.1</span><span>التوقيت: {Intl.DateTimeFormat().resolvedOptions().timeZone} · الوقت محسوب من السيرفر</span></footer></main>
  <Sheet open={!!t} onOpenChange={v=>{if(!v)setSelected(null);}}><SheetContent side="left" className="task-sheet" dir="rtl">
   {t&&<><div className="sheet-top"><SheetTitle>{t.title}</SheetTitle><SheetDescription>تفاصيل التاسك · {t.round>1?`جولة التعديل ${t.round-1}`:'التسليم الأول'}</SheetDescription><div className="button-row"><Badge value={status(t,data)}/>{late(t)&&<span className="overdue">متأخر</span>}</div></div><div className="sheet-body">
    <div className="due-block"><CalendarDays size={21}/><div><small>موعد التسليم</small><b>{date(t.due_at)}</b></div>{ceo&&<Button size="sm" variant="ghost" onClick={()=>open('edit')}>تعديل</Button>}</div>
    <h3>البريف والملفات</h3><p className="prewrap brief">{t.brief}</p><a className="drive-link" href={t.drive_url} target="_blank" rel="noreferrer"><LinkIcon size={18}/>فتح البريف على Google Drive<ArrowUpLeft size={18}/></a>
    <div className="section-title"><h3>المسؤولون عن التنفيذ</h3>{ceo&&!t.approved_at&&<Button size="sm" variant="outline" onClick={()=>open('assign')}><Users size={16}/>توزيع التاسك</Button>}</div>
    {!currentAssignments(t,data).length&&<div className="assignment-empty">التاسك بانتظار توزيع الإدارة قبل بدء التنفيذ.</div>}
    {currentAssignments(t,data).map(a=><div className="assignment-card" key={a.id}><div className="flex-between"><b dir="ltr">{name(a.user_id)}</b><Badge value={a.status}/></div><div className={'timer-display '+(a.running_since?'running':'')}><Clock3 size={19}/><span dir="ltr">{duration(ms(a,time))}</span></div>{a.started_at&&<small className="muted">بدأ: {date(a.started_at)}</small>}{a.submitted_at&&<small className="muted">سلّم: {date(a.submitted_at)}</small>}{a.submitted_at&&<small className="points-inline">+{a.points_awarded||0} نقطة{a.points_reason?` · ${a.points_reason}`:''}</small>}{a.delay_reason&&<p className="delay-box">سبب التأخير: {a.delay_reason}</p>}{a.submission_url&&<a className="drive-link compact" href={a.submission_url} target="_blank" rel="noreferrer">فتح ملفات التسليم<ArrowUpLeft size={16}/></a>}
    {!t.approved_at&&<div className="button-row">{a.user_id===me.id&&a.status==='assigned'&&<Button disabled={busy} onClick={()=>run('start',{...taskPayload(),assignment_id:a.id})}><Play size={16}/>بدء المشروع</Button>}{a.user_id===me.id&&a.status==='working'&&<Button disabled={busy} variant="outline" onClick={()=>run('pause',{...taskPayload(),assignment_id:a.id})}><Pause size={16}/>إيقاف التايمر</Button>}{a.user_id===me.id&&a.status==='paused'&&<Button disabled={busy} variant="outline" onClick={()=>run('resume',{...taskPayload(),assignment_id:a.id})}><Play size={16}/>استكمال</Button>}{a.user_id===me.id&&['working','paused'].includes(a.status)&&<Button onClick={()=>open('submit',a)}><Send size={16}/>تسليم الشغل</Button>}{a.user_id===me.id&&late(t)&&a.status!=='submitted'&&<Button variant="outline" onClick={()=>open('delay',a)}>توضيح سبب التأخير</Button>}</div>}</div>)}
    {ceo&&<div className="ceo-actions"><Button variant="destructive" onClick={()=>open('delete_task')}><Trash2 size={17}/>حذف التاسك</Button>{status(t,data)==='review'&&<Button disabled={busy} onClick={()=>run('approve',taskPayload())}><Check size={18}/>اعتماد التسليم</Button>}{currentAssignments(t,data).length>0&&<Button variant="outline" onClick={()=>open('revision')}><RotateCcw size={17}/>طلب تعديل بموعد جديد</Button>}</div>}
    {data.assignments.some(a=>a.task_id===t.id&&(a.round!==t.round||!a.active))&&<details className="history"><summary>الجولات والتكليفات السابقة</summary>{data.assignments.filter(a=>a.task_id===t.id&&(a.round!==t.round||!a.active)).map(a=><div key={a.id}><b>{name(a.user_id)} · الجولة {a.round}</b><span dir="ltr">{duration(ms(a,time))}</span>{a.submission_url&&<a href={a.submission_url} target="_blank" rel="noreferrer">ملفات التسليم</a>}{a.delay_reason&&<p>{a.delay_reason}</p>}</div>)}</details>}
    <h3>سجل التاسك</h3><div className="activity-list">{data.activity.filter(a=>a.task_id===t.id).map(a=><div key={a.id}><span className="activity-line"/><b>{a.action}</b><small>{name(a.actor)} · {date(a.created_at)}</small>{a.detail&&<p className="prewrap">{a.detail}</p>}</div>)}</div>
   </div></>}
  </SheetContent></Sheet>
  <AlertDialog open={modal==='delete_task'} onOpenChange={v=>{if(!v&&!busy)setModal('');}}><AlertDialogContent dir="rtl"><AlertDialogTitle>حذف التاسك «{t?.title}»؟</AlertDialogTitle><AlertDialogDescription>هيختفي من قوائم الفريق وتتوقف مؤقّتاته. سجله والتسليمات والوقت هتفضل محفوظة في قاعدة البيانات.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>إلغاء</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={busy} onClick={e=>{e.preventDefault();void run('delete_task',taskPayload());}}>تأكيد الحذف</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <Dialog open={!!modal&&modal!=='delete_task'} onOpenChange={v=>{if(!v&&!busy)setModal('');}}><DialogContent className="form-dialog" dir="rtl"><DialogTitle>{({create:'إضافة تاسك',edit:'تعديل التاسك',assign:'توزيع التاسك',submit:'تسليم الشغل',delay:'سبب التأخير',revision:'طلب تعديل',request:'طلب جديد',handle_request:'متابعة الطلب',user:target?'إدارة الحساب':'إضافة عضو',reset:'إعادة تعيين كلمة المرور',password:'تغيير كلمة مروري'} as Record<string,string>)[modal]}</DialogTitle><DialogDescription>{['create','edit','revision'].includes(modal)?'موعد التسليم بالتوقيت المحلي لجهازك.':modal==='assign'?'اختار أي عضو مفعّل، بما فيهم الإدارة، أو أكتر من عضو. إلغاء التكليف يحفظ الوقت والسجل السابق.':modal==='request'?'الإدارة فقط تقدر تشوف وتتابع طلبك.':'راجع البيانات قبل الحفظ.'}</DialogDescription>
   {(modal==='create'||modal==='edit')&&<form key={modal+t?.id} onSubmit={e=>{e.preventDefault();const f=fd(e.currentTarget);run(modal==='create'?'create_task':'edit_task',{...f,...(modal==='edit'?taskPayload():{}),due_at:new Date(String(f.due_at)).toISOString()});}}><Field label="اسم التاسك"><Input name="title" maxLength={180} defaultValue={modal==='edit'?t?.title:''} required/></Field><Field label="البريف / المطلوب"><Textarea name="brief" defaultValue={modal==='edit'?t?.brief:''} rows={4} required/></Field><Field label="لينك Google Drive للبريف والملفات"><Input name="drive_url" type="url" dir="ltr" placeholder="https://drive.google.com/..." defaultValue={modal==='edit'?t?.drive_url:''} required/></Field><Field label="موعد التسليم"><Input name="due_at" type="datetime-local" defaultValue={localDate(modal==='edit'?t?.due_at:undefined)} required/></Field><Button type="submit" disabled={busy}>حفظ التاسك</Button></form>}
   {modal==='assign'&&<form onSubmit={e=>{e.preventDefault();run('assign',{...taskPayload(),user_ids:checks});}}><div className="assignee-picker">{data.profiles.filter(p=>p.active).map(p=><label key={p.id}><Checkbox checked={checks.includes(p.id)} onCheckedChange={v=>setChecks(v?[...checks,p.id]:checks.filter(x=>x!==p.id))}/><span className="avatar">{initials(p.name)}</span><b dir="ltr">{p.name}</b></label>)}</div><Button type="submit" disabled={busy||!checks.length}>حفظ التوزيع</Button></form>}
   {(modal==='submit'||modal==='delay')&&<form onSubmit={e=>{e.preventDefault();run(modal==='submit'?'submit':'delay',{...fd(e.currentTarget),...taskPayload(),assignment_id:target.id});}}>{modal==='submit'&&<Field label="لينك Drive لملفات التسليم"><Input name="submission_url" type="url" dir="ltr" required/></Field>}<Field label={t&&late(t)?'سبب التأخير — إجباري':'ملاحظة / سبب التأخير إن وجد'}><Textarea name="delay_reason" defaultValue={target?.delay_reason||''} required={modal==='delay'||!!t&&late(t)}/></Field><Button type="submit" disabled={busy}>{modal==='submit'?'تسليم للمراجعة':'حفظ السبب'}</Button></form>}
   {modal==='revision'&&<form onSubmit={e=>{e.preventDefault();const f=fd(e.currentTarget);run('revision',{...taskPayload(),note:f.note,due_at:new Date(String(f.due_at)).toISOString()});}}><Field label="التعديلات المطلوبة"><Textarea name="note" rows={5} required/></Field><Field label="موعد تسليم التعديل"><Input name="due_at" type="datetime-local" defaultValue={localDate()} required/></Field><p className="muted">هتبدأ جولة جديدة لنفس الموظفين، مع الاحتفاظ بوقت وتسليم الجولة السابقة.</p><Button type="submit" disabled={busy}>إرسال التعديل</Button></form>}
   {modal==='request'&&<form onSubmit={e=>{e.preventDefault();run('create_request',{...fd(e.currentTarget),kind:choice});}}><Field label="نوع الطلب"><Pick value={choice} onChange={setChoice} items={kinds}/></Field><Field label="العنوان"><Input name="title" maxLength={180} required/></Field><Field label="التفاصيل"><Textarea name="body" rows={5} required/></Field><Button type="submit" disabled={busy}>إرسال للإدارة</Button></form>}
   {modal==='handle_request'&&<form onSubmit={e=>{e.preventDefault();const f=fd(e.currentTarget);run('update_request',{...f,id:target.id,status:choice,execution_due_at:f.execution_due_at?new Date(String(f.execution_due_at)).toISOString():''});}}><h3>{target?.title}</h3><p className="prewrap">{target?.body}</p><Field label="حالة الطلب"><Pick value={choice} onChange={setChoice} items={requestLabels}/></Field>{choice==='progress'&&<Field label="موعد التنفيذ — إجباري عند الموافقة"><Input name="execution_due_at" type="datetime-local" defaultValue={target?.execution_due_at?localDate(target.execution_due_at):localDate()} required/></Field>}<Field label="رد الإدارة"><Textarea name="response" defaultValue={target?.response} rows={4}/></Field><div className="button-row"><Button type="submit" disabled={busy}>حفظ المتابعة</Button><Button type="button" variant="destructive" disabled={busy} onClick={()=>{if(confirm('حذف الطلب/الشكوى؟'))void run('delete_request',{id:target.id});}}>حذف الطلب</Button></div></form>}
   {modal==='user'&&<form onSubmit={e=>{e.preventDefault();manage({...fd(e.currentTarget),action:target?'update_user':'create_user',user_id:target?.id,role:choice,active});}}><Field label="الاسم"><Input name="name" defaultValue={target?.name} maxLength={100} required/></Field>{!target&&<><Field label="اسم المستخدم — حروف إنجليزية صغيرة وأرقام ونقطة"><Input name="username" dir="ltr" pattern="[a-z0-9.]{3,40}" required/></Field><Field label="كلمة مرور مؤقتة — 12 حرفًا على الأقل"><Input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></Field></>}<Field label="الصلاحية"><Pick value={choice} onChange={setChoice} items={roleLabel}/></Field>{target&&<label className="switch-row"><Switch checked={active} onCheckedChange={setActive}/>الحساب مفعّل</label>}<Button type="submit" disabled={busy}>حفظ الحساب</Button></form>}
   {(modal==='reset'||modal==='password')&&<form onSubmit={e=>{e.preventDefault();const f=fd(e.currentTarget);if(f.password!==f.confirm){toast.error('كلمتا المرور غير متطابقتين.');return;}manage({...f,action:modal==='reset'?'reset_password':'change_password',user_id:target?.id});}}>{modal==='password'&&<Field label="كلمة المرور الحالية"><Input name="current_password" type="password" autoComplete="current-password" required/></Field>}<Field label="كلمة مرور جديدة — 12 حرفًا على الأقل"><Input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></Field><Field label="تأكيد كلمة المرور"><Input name="confirm" type="password" autoComplete="new-password" required/></Field><Button type="submit" disabled={busy}>حفظ كلمة المرور</Button></form>}
  </DialogContent></Dialog>
 </div>;
}
