-- Remote migration history marker for 20261001124408_v12_workflow_indexes.
-- This migration is already applied on the linked production Supabase project.
-- Do not add schema-changing SQL here. Canonical implementation SQL is retained under /database.
