-- Remote migration history marker for 20260923113814_team_assignment_private_chat_notifications.
-- This migration is already applied on the linked production Supabase project.
-- Do not add schema-changing SQL here. Canonical implementation SQL is retained under /database.
