-- Remote migration history marker for 20260923002329_brivviant_team_workspace.
-- This migration is already applied on the linked production Supabase project.
-- Do not add schema-changing SQL here. Canonical implementation SQL is retained under /database.
