-- Remote migration history marker for 20261001122954_v12_web_push_trigger.
-- This migration is already applied on the linked production Supabase project.
-- Do not add schema-changing SQL here. Canonical implementation SQL is retained under /database.
