-- Remote migration history marker for 20260923153229_requests_timer_activity_v7.
-- This migration is already applied on the linked production Supabase project.
-- Do not add schema-changing SQL here. Canonical implementation SQL is retained under /database.
