-- Remote migration history marker for 20260923112227_restore_required_drive_links.
-- This migration is already applied on the linked production Supabase project.
-- Do not add schema-changing SQL here. Canonical implementation SQL is retained under /database.
