-- Remote migration history marker for 20261001122609_v12_project_scoring_functions.
-- This migration is already applied on the linked production Supabase project.
-- Do not add schema-changing SQL here. Canonical implementation SQL is retained under /database.
